### ISSUE TITLE
my todo list for this

### ISSUE THREAD

**Issue by wgyt** [wgyt/-1hostjs-1.0compatibilitylayer#1]
- [x] replace res.send with res.start but add some compatibility tweaks
- [x] replace res.status with the http equivalent but add some compatibility tweaks
- [x] replace the empty function with fake error handler?
